version: '3.4'

services:
   sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@User123456!"
    ports:
      - 1430:1433
    volumes:
      - sql_data:/var/opt/mssql

   faceai.webapi:
    image: ${DOCKER_REGISTRY-}faceaiwebapi
    build:
      context: .
      dockerfile: FaceAI.WebApi/Dockerfile

volumes:
    sql_data:
       

